export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const GET_CURRENT_EMPLOYEE = "GET_CURRENT_EMPLOYEE";
export const RESET_CURRENT_EMPLOYEE = "RESET_CURRENT_EMPLOYEE";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";